<html>
 <head></head>
 <body>
  <p>As you already know, an exception interrupts the normal execution of a program. Normally this is not what we want to happen. Luckily, it is possible to write some code that will handle the exception without stopping the whole program. To do that, Java provides an <strong>exception handling</strong> mechanism that works with both <strong>checked</strong> and <strong>unchecked</strong> exceptions.</p>
  <h4>How to handle an exception</h4>
  <p>After a line of code throws an exception, the Java runtime system attempts to find a suitable handler for it. Such a handler can be located in the same method where the exception occurred or in the calling method. As soon as a suitable handler is found and executed, the exception is considered as handled and the program runs normally.</p>
  <p>Technically, an exception can be handled in the method where it occurs or in the calling method. The best approach to handle an exception is to do it in a method that has sufficient information to make the correct decision based on this exception.</p>
  <p>Let's now learn three keywords for handling exceptions: <code>try</code>, <code>catch</code> and <code>finally</code>.</p>
  <h4>The try-catch statement</h4>
  <p>Here is a simple <code>try-catch</code> template for handling exceptions:</p>
  <pre><code>try {
    // code that may throw an exception
} catch (Exception e) {
    // code for handling the exception
}</code></pre>
  <p>The <code>try</code> block is used to wrap the code that may throw an exception. This block can include all lines of code, including method calls.</p>
  <p>The <code>catch</code> block is a handler for the specified type of exception and all of its subclasses. This block is executed when an exception of the corresponding type occurs in the <code>try</code> block.</p>
  <p></p>
  <div class="alert alert-warning">
   <p>Note that the specified type in a <code>catch</code> block must extend the <code>Throwable</code> class.</p>
  </div>
  <p></p>
  <p>In the presented template, the <code>catch</code> block can handle exceptions of the <code>Exception</code> class and all classes derived from it.</p>
  <p>The following example demonstrates the execution flow with <code>try</code> and <code>catch</code>.</p>
  <pre><code>System.out.println("before the try-catch block"); // it will be printed

try {
    System.out.println("inside the try block before an exception"); // it will be printed

    System.out.println(2 / 0); // it throws ArithmeticException

    System.out.println("inside the try block after the exception"); // it won't be printed
} catch (Exception e) {
    System.out.println("Division by zero!"); // it will be printed
}

System.out.println("after the try-catch block"); // it will be printed</code></pre>
  <p>The output:</p>
  <pre><code>before the try-catch block
inside the try block before an exception
Division by zero!
after the try-catch block</code></pre>
  <p>The program does not print <code>"inside the try block after the exception"</code> since the <code>ArithmeticException</code> aborted the normal flow of the execution. Instead, it executes the print statement in the <code>catch</code> block. After completion of the <code>catch</code> block, the program executes the next statement (printing <code>"after the try-catch block"</code>) without returning to the <code>try</code> block again.</p>
  <p>Replacing <code>Exception</code> with <code>ArithmeticException</code> or <code>RuntimeException</code> in the <code>catch</code> statement does not change the execution flow of the program. But replacing it with <code>NumberFormatException</code> will make the handler unsuitable for the exception and the program will fail.</p>
  <p></p>
  <div class="alert alert-primary">
   <p>As we noted earlier, the <code>try-catch</code> statement can handle both checked and unchecked exceptions. But there is a difference: checked exceptions must be wrapped with a <code>try-catch</code> block or declared to be thrown in the method, while unchecked exceptions don't have to.</p>
  </div>
  <p></p>
  <h4>Getting info about an exception</h4>
  <p>When an exception is caught by a <code>catch</code> block, it is possible to get some information on it:</p>
  <pre><code>try {
    double d = 2 / 0;
} catch (Exception e) {
    System.out.println(e.getMessage());
}</code></pre>
  <p>This code prints:</p>
  <pre><code>An exception occured: / by zero</code></pre>
  <h4>Catching multiple exceptions</h4>
  <p>It is always possible to use a single handler for all types of exceptions:</p>
  <pre><code>try {
    // code that may throw exceptions
} catch (Exception e) {
    System.out.println("Something goes wrong");
}</code></pre>
  <p>Obviously, this approach does not allow us to perform different actions depending on the type of exception that has occurred. Fortunately, Java supports the use of several handlers inside the same <code>try</code> block.</p>
  <pre><code>try {
    // code that throws exceptions
} catch (IOException e) {
    // handling the IOException and its subclasses    
} catch (Exception e) {
    // handling the Exception and its subclasses
}</code></pre>
  <p>When an exception occurs in the <code>try</code> block, the runtime system determines the first suitable <code>catch</code> block according to the type of the exception. Matching goes from top to bottom.</p>
  <p></p>
  <div class="alert alert-warning">
   <p>Important, the <code>catch</code> block with the base class has to be written below all blocks with subclasses. In other words, the more specialized handlers (like <code>IOException</code>) must be written before the more general ones (like <code>Exception</code>). Otherwise, the code won't compile.</p>
  </div>
  <p></p>
  <p>Since Java 7, you can use a <strong>multi-catch </strong>syntax to have several exceptions handled in the same way:</p>
  <pre><code>try {
    // code that may throw exceptions
} catch (SQLException | IOException e) {
    // handling SQLException, IOException and their subclasses
    System.out.println(e.getMessage());
} catch (Exception e) {
    // handling any other exceptions
    System.out.println("Something goes wrong");
}</code></pre>
  <p>In the code above <code>SQLException</code> and <code>IOException</code> (alternatives) are separated by the <code>|</code> character. They will be handled in the same way.</p>
  <p></p>
  <div class="alert alert-warning">
   <p>Note that alternatives in a multi-catch statement cannot be each other's subclasses.</p>
  </div>
  <p></p>
  <h4>The finally block</h4>
  <p>There is another possible block called <code>finally</code>. All statements present in this block will always execute regardless of whether an exception occurs in the <code>try</code> block or not.</p>
  <pre><code>try {
    // code that may throw an exception
} catch (Exception e) {
    // exception handler
} finally {
    // code that will always be executed
}</code></pre>
  <p>The following example illustrates the order of execution of the <code>try-catch-finally</code> statement.</p>
  <pre><code>try {
    System.out.println("inside the try block");
    Integer.parseInt("101abc"); // throws a NumberFormatException
} catch (Exception e) {
    System.out.println("inside the catch block");
} finally {
    System.out.println("inside the finally block");
}

System.out.println("after the try-catch-finally block");</code></pre>
  <p>The output:</p>
  <pre><code>inside the try block
inside the catch block
inside the finally block
after the try-catch-finally block</code></pre>
  <p>If we remove the line that throws a <code>NumberFormatException</code>, the <code>finally</code> block is still executed after the <code>try</code> block.</p>
  <pre><code>inside the try block
inside the finally block
after the try-catch-finally block</code></pre>
  <p></p>
  <div class="alert alert-primary">
   <p>Interesting: the <code>finally</code> block is executed even if an exception occurs in the <code>catch</code> block.</p>
  </div>
  <p></p>
  <p>It is also possible to write <code>try</code> and <code>finally</code> without a <code>catch</code> block at all.</p>
  <pre><code>try {
    // code that may throw an exception
} finally {   
    // code always be executed
}</code></pre>
  <p>In this template, the <code>finally</code> block is executed right after the <code>try</code> block.</p>
  <h4>Conclusion</h4>
  <p>The <code>try-catch</code> statement allows us to handle both checked and unchecked exceptions .</p>
  <p>The <code>try</code> block wraps the code that may throw an exception while the <code>catch</code> block handles this exception in case it occurs, also allowing us to get some information about it. It is possible to use several handlers to provide different scenarios for different types of exceptions.</p>
  <p>Finally, there's an optional <code>finally</code> block that is always executed. Its main feature is that it executes even if we fail to handle an exception at all.</p>
 </body>
</html>